# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

pod 'Firebase'
pod 'Alamofire', '~> 3.4'

target 'collegemate' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  
  pod 'SwiftyJSON'  

  # Pods for collegemate

  target 'collegemateTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
